POST http://localhost:3005/add-user HTTP/1.1
content-type: application/json

{
    
"name":"nabbu",
"address":"tikapur",
"email":"nbn@gmail.com",
"username":"nbnr",
"password":"nabin11",
"type":"user"
}
